"""initial

Revision ID: 5497fec79949
Revises: 
Create Date: 2026-02-13 21:55:36.086654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5497fec79949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('brokerage', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('holding_count', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('brokerage', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'label', name='uq_dimension_label')
    )
    op.create_table('ticker_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('region_breakdown', sa.JSON(), nullable=False),
    sa.Column('category_breakdown', sa.JSON(), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_classifications')
    op.drop_table('target_allocations')
    op.drop_table('holdings')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
