"""add portfolio_analyses table

Revision ID: 87bdb90f634a
Revises: 5497fec79949
Create Date: 2026-02-14 00:09:11.176447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bdb90f634a'
down_revision = '5497fec79949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_analyses_snapshot_date'), ['snapshot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_analyses_snapshot_date'))

    op.drop_table('portfolio_analyses')
    # ### end Alembic commands ###
